export enum MedicationRequestTimelineAction {
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  NEEDS_MORE_INFO = "NEEDS_MORE_INFO",
  CANCELLED = "CANCELLED",
  PARENT_RESPONDED = "PARENT_RESPONDED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}

export enum MedicationRequestTimelineActorType {
  GUARDIAN = "GUARDIAN",
  STAFF = "STAFF",
  SYSTEM = "SYSTEM",
}
