export enum MedicationRequestStatus {
  SUBMITTED = "SUBMITTED",
  NEEDS_MORE_INFO = "NEEDS_MORE_INFO",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}
