export enum AttendanceRollCallState {
  IN_CLASS = "IN_CLASS",
  ABSENCE_WITH_REQUEST = "ABSENCE_WITH_REQUEST",
  ABSENCE_WITHOUT_REQUEST = "ABSENCE_WITHOUT_REQUEST",
  NOT_IDENTIFIED = "NOT_IDENTIFIED",
}
