export enum AttendanceChangeType {
  STATUS_CHANGED = "STATUS_CHANGED",
  NOTE_CHANGED = "NOTE_CHANGED",
  ABSENCE_REQUEST_CHANGED = "ABSENCE_REQUEST_CHANGED",
  APPROVED_ABSENCE_OVERRIDDEN = "APPROVED_ABSENCE_OVERRIDDEN",
}
